# Site Info
title: ""
tagline: ""
description: ""
baseurl: ""
url: https://onssu.github.io
logo: ""

# Site configurations
#gems:
#  - jekyll-paginate
#markdown: kramdown
#kramdown:
#  input: GFM
#excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
#paginate:
#paginate_path: ''
#permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Yuri Kim
  description: Yuri Kim
  contact:
    # linkedin:  https://www.linkedin.com/in/
    github: https://github.com/onssu
    #    facebook:
    # twitter:
    # weibo:
    email: mailto:onssu1@gmail.com

google_analytics:
  ua: "UA-134234881-1"
